version: "3.8"

services:
  # === SERVICES ===
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - recipe-service
      - review-service

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo-user:27017/userdb
    depends_on: [mongo-user, rabbitmq]

  recipe-service:
    build: ./recipe-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URL=mongodb://mongo-recipe:27017/recipedb
    depends_on: [mongo-recipe, rabbitmq]

  review-service:
    build: ./review-service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URL=mongodb://mongo-review:27017/reviewdb
    depends_on: [mongo-review, rabbitmq]

  # === DATABASE ====
  mongo-user:
    image: mongo
    ports: ["27017:27017"]
    volumes: [mongo-user-data:/data/db]

  mongo-recipe:
    image: mongo
    ports: ["27018:27017"]
    volumes: [mongo-recipe-data:/data/db]

  mongo-review:
    image: mongo
    ports: ["27019:27017"]
    volumes: [mongo-review-data:/data/db]

  # === RABBITMQ ===
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  mongo-user-data:
  mongo-recipe-data:
  mongo-review-data:
