version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./shared:/app/shared
    depends_on:
      - user-service
      - recipe-service
      - review-service

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo-user:27017/userdb
      - PORT=8001
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - ./shared:/app/shared
    depends_on:
      - mongo-user
      - rabbitmq

  recipe-service:
    build: ./recipe-service
    ports:
      - "8002:8002"
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo-recipe:27017/recipedb
      - PORT=8002
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - ./shared:/app/shared
    depends_on:
      - mongo-recipe
      - rabbitmq

  review-service:
    build: ./review-service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URL=mongodb://mongo-review:27017/reviewdb
      - PORT=8003
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - ./shared:/app/shared
    depends_on:
      - mongo-review
      - rabbitmq

  mongo-user:
    image: mongo
    ports: ["27017:27017"]
    volumes: [mongo-user-data:/data/db]

  mongo-recipe:
    image: mongo
    ports: ["27018:27017"]
    volumes: [mongo-recipe-data:/data/db]

  mongo-review:
    image: mongo
    ports: ["27019:27017"]
    volumes: [mongo-review-data:/data/db]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo-user-data:
  mongo-recipe-data:
  mongo-review-data:
