apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: evasbr/recipe-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: MONGO_URL
              value: mongodb://mongo-recipe:27017/recipedb
            - name: PORT
              value: "8002"
            - name: JWT_SECRET
              value: akmdlkamdawiodalkdmo340239u
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
