apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: evasbr/review-service:latest
          ports:
            - containerPort: 8003
          env:
            - name: MONGO_URL
              value: mongodb://mongo-review:27017/reviewedb
            - name: PORT
              value: "8003"
            - name: JWT_SECRET
              value: akmdlkamdawiodalkdmo340239u
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
