apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: evasbr/user-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_URL
              value: mongodb://mongo-user:27017/userdb
            - name: PORT
              value: "8001"
            - name: JWT_SECRET
              value: akmdlkamdawiodalkdmo340239u
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
